# Advanced Concepts {#advanced_concepts} 

## Entropy and Cross-Entropy

- [Demystifying Entropy](https://towardsdatascience.com/demystifying-entropy-f2c3221e2550)
- [Demystifying Cross Entropy](https://towardsdatascience.com/demystifying-cross-entropy-e80e3ad54a8)

## Word2Vec

- [Word2Vec Tutorial- The Skip-Gram Model](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/)
- [Word2Vec Tutorial Part 2 - Negative Sampling](http://mccormickml.com/2017/01/11/word2vec-tutorial-part-2-negative-sampling/)

## Stationarity and Differencing in Time-Series

- [Forecasting: Principles and Practice - Stationarity and Differencing](https://otexts.com/fpp2/stationarity.html)

## Autocorrelation

- [Autocorrelation and Partial Autocorrelation Functions](https://www.ibm.com/support/knowledgecenter/en/SS3RA7_15.0.0/com.ibm.spss.modeler.help/timeseries_acf_pacf.htm)
- [What is the autocorrelation function?](https://stats.stackexchange.com/questions/77248/what-is-autocorrelation-function)
- [Identifying the numbers of AR or MA terms in an ARIMA model](http://people.duke.edu/~rnau/411arim3.htm)
- [Model Identification](https://www.itl.nist.gov/div898/handbook/pmc/section6/pmc622.htm)

## Maximum Likelihood Estimation vs. Bayesian Estimation

- [Maximum Likelihood Estimation and Bayesian Estimation](https://www.youtube.com/watch?v=fjqd0gG-5OE&feature=youtu.be)
- [What is the difference between Bayesian estimate and maximum likelihood estimate?](https://stats.stackexchange.com/questions/74082/what-is-the-difference-in-bayesian-estimate-and-maximum-likelihood-estimate)
- [Explaining Maximum Likelihood, Maximum a Posteriori, and Bayesian Parameter Estimation](https://medium.com/@amatsukawa/maximum-likelihood-maximum-a-priori-and-bayesian-parameter-estimation-d99a23a0519f)

## Local-Interpretable-Model-Agnostic Explanations (LIME)

## Generalized Additive Models (GAMs)

## Attention
