# Datasets {#datasets} 

- [Introducing TensorFlow Datasets (February 2019, Medium)](https://medium.com/tensorflow/introducing-tensorflow-datasets-c7f01f7e19f3)
    - "Today, we’re pleased to introduce TensorFlow Datasets (GitHub) which exposes public research datasets as `tf.data.Datasets` and as NumPy arrays. It does all the grungy work of fetching the source data and preparing it into a common format on disk, and it uses the `tf.data API` to build high-performance input pipelines, which are TensorFlow 2.0-ready and can be used with `tf.keras` models. We’re launching with 29 popular research datasets such as MNIST, Street View House Numbers, the 1 Billion Word Language Model Benchmark, and the Large Movie Reviews Dataset, and will add more in the months to come; we hope that you join in and add a dataset yourself."
- [Google Dataset Search](https://toolbox.google.com/datasetsearch)
    - [Google launches new search engine to help scientists find the datasets they need (September 2018, The Verge)](https://www.theverge.com/2018/9/5/17822562/google-dataset-search-service-scholar-scientific-journal-open-data-access)