# General Resources {#general}

## Intro to ML Resources

### Introductory Videos

- [How Does Your Phone Know This Is A Dog? (September 2015, Youtube)](https://www.youtube.com/watch?v=bHvf7Tagt18&feature=youtu.be)
- [Behind the Mic: The Science of Talking with Computers (October 2014, Youtube)](https://www.youtube.com/watch?v=yxxRAHVtafI&feature=youtu.be)

### Business & Product Management

- [Machine Learning & AI: When To Start? (May 2017, Shelly Palmer)](https://www.shellypalmer.com/2017/05/machine-learning-ai-start/)
- [What Every Manager Should Know About Machine Learning (July 2015, HBR)](https://hbr.org/2015/07/what-every-manager-should-know-about-machine-learning)
- [The Step-By-Step PM Guide to Building Machine Learning Based Products (July 2017, Medium)](https://medium.com/@yaelg/product-manager-pm-step-by-step-tutorial-building-machine-learning-products-ffa7817aa8ab)

### How Does It Work?

- [a16z AI Playbook](http://aiplaybook.a16z.com)
    - “This microsite is intended to help newcomers (both non-technical and technical) begin exploring what's possible with AI”
- [A Visual Introduction to Machine Learning](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/)
- [Machine Learning Is Fun! (May 2014, Medium)](https://medium.com/@ageitgey/machine-learning-is-fun-80ea3ec3c471)
    - Great intro for folks with a slightly technical background
- [Machine Learning For Humans (August 2017, Medium)](https://medium.com/machine-learning-for-humans/why-machine-learning-matters-6164faf1df12)
    - A technically-oriented intro

## Market Trends and Reports

- [The State of AI in 2019 (The Verge, 2019)](https://www.theverge.com/2019/1/28/18197520/ai-artificial-intelligence-machine-learning-computational-science)
- [State of AI (August 2018)](https://www.stateof.ai/)
- [Ways to think about machine learning (June 2018, Benedict Evans Blog)](https://www.ben-evans.com/benedictevans/2018/06/22/ways-to-think-about-machine-learning-8nefy)
- [The Global Innovation Sweepstakes (June 2018, Atlantic Council)](http://www.atlanticcouncil.org/images/publications/The-Global-Innovation-Sweepstakes.pdf)
- [The WIRED Guide to Artificial Intelligence (Feb 2018, Wired)](https://www.wired.com/story/guide-artificial-intelligence/)
- [The AI Revolution: The Road to Superintelligence (January 2015, Wait but Why?)](https://waitbutwhy.com/2015/01/artificial-intelligence-revolution-1.html)
- [The state of Artificial Intelligence - Recent advances, startups, the road ahead (November 2017, CB Insights)](https://drive.google.com/file/d/1sy8aOvQs5IyeRAptomfQcijHB2CjpCxS/view)
- [Artificial Intelligence: The next digital frontier? (June 2017, McKinsey)](https://drive.google.com/file/d/0B9TPrZu6o5q-LVozMnBJS3VnOHc/view)
- [Perspectives on Artificial Intelligence (Q3 2017, Digital Capital Advisors)](https://drive.google.com/file/d/0B9TPrZu6o5q-N0pMcjlaY0MxbzQ/view)
- [Artificial Intelligence - AI, Machine Learning & Data Fuel The Future of Productivity (Nov 2017, Goldman Sachs)](https://drive.google.com/file/d/0B9TPrZu6o5q-RTdJdzFiVk80OFU/view)
- [15 tech trends in autonomous cars, artificial intelligence, and machine learning for 2017 (December 2016, Venturebeat)](https://venturebeat.com/2018/02/19/sk-telecom-will-demo-5g-social-vr-self-driving-cars-and-hologram-ai-at-mwc-2018/)
- [Machine Learning Industry Predictions: Expert Consensus (March 2017, TechEmergence)](https://www.techemergence.com/machine-learning-industry-predictions-expert-consensus/)
- [The Current State of Machine Intelligence 3.0 (2016, Shivon Zilis)](http://www.shivonzilis.com/)
- [The State of Machine Intelligence (2016, HBR)](https://hbr.org/resources/pdfs/hbr-articles/2016/11/the_state_of_machine_intelligence.pdf)
- [Gartner's Top 10 Predictions For IT In 2018 And Beyond (October 2017, Forbes)](https://www.forbes.com/sites/louiscolumbus/2017/10/03/gartners-top-10-predictions-for-it-in-2018-and-beyond/#39b7b71b45bb)
- [The Royal Society Machine Learning](https://royalsociety.org/topics-policy/projects/machine-learning/)
- [Inside the Alexa Prize (Feb 2018, Wired)](https://www.wired.com/story/inside-amazon-alexa-prize/)
- [Google's New AI Head Is So Smart He Doesn't Need AI (April 2018, Wired)](https://www.wired.com/story/googles-new-ai-head-is-so-smart-he-doesnt-need-ai/)
- [How babies learn – and why robots can’t compete (April 2018, The Guardian)](https://www.theguardian.com/news/2018/apr/03/how-babies-learn-and-why-robots-cant-compete)

## AI + ML Blogs

### Intuitive explanations of technical concepts

- [Chris Colah's Blog](http://colah.github.io)
- [Andrej Karpathy's Blog](http://karpathy.github.io)

### Technical blogs on latest research

- [Distill](https://distill.pub)
    - Online journal started by Google Brain team members dedicated to clear explanations of ML concepts
- [Google AI Blog](https://ai.googleblog.com)
- [Google Brain Team](https://ai.google/research/teams/brain)
    - [Looking Back on 2017](https://ai.googleblog.com/2018/01/the-google-brain-team-looking-back-on.html)
    - [Looking Back on 2016](https://ai.googleblog.com/2017/01/the-google-brain-team-looking-back-on.html)
- [Research at Google Publications](https://ai.google/research/pubs/)
- [DeepMind Blog](https://deepmind.com/blog/)
- [DeepMind Publications](https://deepmind.com/research/publications/)
- [Papers With Code](https://paperswithcode.com)
    - "Highlights trending ML research and the code to implement it."

## Interviews + Talks with AI Experts

- [Jeff Dean’s Lecture for YC AI (August 2017)](https://www.youtube.com/watch?v=HcStlHGpjN8&t=1223s)
- [Making Computers Smarter with Google's AI chief John Giannandrea | Disrupt SF 2017 (September 2017)](https://www.youtube.com/watch?v=djkeV4gew4Q)
- [Past, Present and Future of AI / Machine Learning (Google I/O '17) (May 2017)](https://www.youtube.com/watch?v=0ueamFGdOpA)
- [Garry Kasparov: "Deep Thinking" | Talks at Google (June 2017)](https://www.youtube.com/watch?v=zhkTHkIZJEc)
- [Mustafa Suleyman: How DeepMind vanquished Go (April 2017)](https://www.ft.com/deepmind?mhq5j=e3)

## Online Courses

- [Amazon's online course](https://aws.amazon.com/training/learning-paths/machine-learning/)
- [Andrew Ng’s Coursera course](https://www.coursera.org/learn/machine-learning)
- [AI for Everyone - Andrew Ng Coursera course](https://www.coursera.org/learn/ai-for-everyone/)
- [Geoff Hinton’s Coursera course](https://www.coursera.org/learn/neural-networks)
- [DeepMind / Oxford Deep Learning course](http://github.com/oxford-cs-deepnlp-2017/lectures)