# Getting Up To Speed {#guts}

## Must Reads!

If you only have time to read a few articles and feel overwhelmed by all the resources, here are a few gems we pulled out:

- [The Great AI Awakening (Dec 2016, NYT)](https://www.nytimes.com/2016/12/14/magazine/the-great-ai-awakening.html?_r=0)
- [What AI can and can’t do (yet) for your business (Jan 2018, Mckinsey)](https://www.mckinsey.com/business-functions/mckinsey-analytics/our-insights/what-ai-can-and-cant-do-yet-for-your-business)
- [Notes From the AI Frontier: Modeling the Impact of AI on the World Economy (April 2018, McKinsey)](https://www.mckinsey.com/~/media/McKinsey/Featured%20Insights/Artificial%20Intelligence/Notes%20from%20the%20frontier%20Modeling%20the%20impact%20of%20AI%20on%20the%20world%20economy/MGI-Notes-from-the-AI-frontier-Modeling-the-impact-of-AI-on-the-world-economy-September-2018.ashx)
- [Google 2017 Founders’ Letter](https://abc.xyz/investor/founders-letters/2017/index.html)
- [Learn with Google AI](https://ai.google/education)

## General

### Market Trends and Reports

### Intro to ML Resources

#### Introductory Videos

- [How Does Your Phone Know This Is A Dog?](https://www.youtube.com/watch?v=bHvf7Tagt18&feature=youtu.be)
- [Behind the Mic: The Science of Talking with Computers](https://www.youtube.com/watch?v=yxxRAHVtafI&feature=youtu.be)

#### Business & Product Management

- [Machine Learning & AI: When to Start?](https://www.shellypalmer.com/2017/05/machine-learning-ai-start/)
- [What Every Manager Should Know About Machine Learning](https://hbr.org/2015/07/what-every-manager-should-know-about-machine-learning)
- [The Step-By-Step PM Guide to Building Machine Learning Based Products](https://medium.com/@yaelg/product-manager-pm-step-by-step-tutorial-building-machine-learning-products-ffa7817aa8ab)

#### How Does It Work?

- [a16z AI Playbook](http://aiplaybook.a16z.com)
    - “This microsite is intended to help newcomers (both non-technical and technical) begin exploring what's possible with AI”
- [A Visual Introduction to Machine Learning](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/)
- [Machine Learning Is Fun!](https://medium.com/@ageitgey/machine-learning-is-fun-80ea3ec3c471)
    - Great intro for folks with a slightly technical background
- [Machine Learning For Humans](https://medium.com/machine-learning-for-humans/why-machine-learning-matters-6164faf1df12)
    - A technically-oriented intro

### AI + ML Blogs

#### Intuitive explanations of technical concepts

- [Chris Colah's Blog](http://colah.github.io)
- [Andrej Karpathy's Blog](http://karpathy.github.io)

#### Technical blogs on latest research

- [Distill](https://distill.pub)
    - Online journal started by Google Brain team members dedicated to clear explanations of ML concepts
- [Google AI Blog](https://ai.googleblog.com)
- [Google Brain Team](https://ai.google/research/teams/brain)
    - [Looking Back on 2017](https://ai.googleblog.com/2018/01/the-google-brain-team-looking-back-on.html)
    - [Looking Back on 2016](https://ai.googleblog.com/2017/01/the-google-brain-team-looking-back-on.html)
- [Research at Google Publications](https://ai.google/research/pubs/)
- [DeepMind Blog](https://deepmind.com/blog/)
- [DeepMind Publications](https://deepmind.com/research/publications/)

### Interviews + Talks with AI Experts

### Online Courses

## Industries

### Energy

- [Artificial Intelligence and the Future of Energy](https://medium.com/wepower/artificial-intelligence-and-the-future-of-energy-105ac6053de4)
- [How Artificial Intelligence Will Revolutionize the Energy Industry](http://sitn.hms.harvard.edu/flash/2017/artificial-intelligence-will-revolutionize-energy-industry/)
- [5 Ways the Energy Industry is Using Artificial Intelligence](https://www.cbinsights.com/research/artificial-intelligence-energy-industry/)
- [This AI Just Mapped Every Solar Panel in the US](https://gizmodo.com/this-ai-just-mapped-every-solar-panel-in-the-united-sta-1831200756)

### Earth, Environment, and Climate Change

- [Harnessing Artificial Intelligence for the Earth](http://www3.weforum.org/docs/Harnessing_Artificial_Intelligence_for_the_Earth_report_2018.pdf)
- [Global Fishing Watch tracks ocean poachers with the help of AI](https://venturebeat.com/2018/06/08/global-fishing-watch-tracks-ocean-poachers-with-the-help-of-ai/)
- [AI is helping seismologists detect earthquakes they’d otherwise miss](https://www.theverge.com/2018/2/14/17011396/ai-earthquake-detection-oklahoma-neural-network)
    - Thibaut Perol (a deep learning researcher from Harvard) is looking into the use of AI to amplify the sensitivity of the state’s seismographs. This paper^[http://advances.sciencemag.org/content/4/2/e1700578] published in the journal Science Advances shows how effective this technique is - capable of detecting 17 times more earthquakes than older methods in a fraction of the time.
- [The fight against illegal deforestation with TensorFlow](https://blog.google/topics/machine-learning/fight-against-illegal-deforestation-tensorflow/)
- [Facebook AI Researchers Detect Flood and Fire Damage from Satellite Imagery](https://venturebeat.com/2018/12/07/facebook-ai-researchers-detect-flood-and-fire-damage-from-satellite-imagery/)

### Health

### Law

### Art

### Transportation

### Robotics

## Themes

### Jobs

### China and AI

### Nations Investing in AI

### Artificial General Intelligence (AGI)

### Ethics

#### General

#### AI Weapons

#### Black Box & Model Explainability

#### Model Bias

#### Fake News

### AI + ML Skepticism

### AI + Neuroscience

### Security
