# Industry Applications {#industry}

## Art

- [Is artificial intelligence set to become art’s next medium? (October 20018, Christies)](https://www.christies.com/features/A-collaboration-between-two-artists-one-human-one-a-machine-9332-1.aspx)
- [Google's AI scans and tags millions of 'Life' magazine photos (March 2018, Engadget)](https://www.engadget.com/2018/03/07/googles-ai-scans-and-tags-millions-of-life-magazine-photos/)

## Earth, Environment, and Climate Change

- [Harnessing Artificial Intelligence for the Earth (2018, World Economic Forum)](http://www3.weforum.org/docs/Harnessing_Artificial_Intelligence_for_the_Earth_report_2018.pdf)
- [Global Fishing Watch tracks ocean poachers with the help of AI (June 2018, VentureBeat)](https://venturebeat.com/2018/06/08/global-fishing-watch-tracks-ocean-poachers-with-the-help-of-ai/)
- [AI is helping seismologists detect earthquakes they’d otherwise miss (Feb 2018, Verge)](https://www.theverge.com/2018/2/14/17011396/ai-earthquake-detection-oklahoma-neural-network)
    - Thibaut Perol (a deep learning researcher from Harvard) is looking into the use of AI to amplify the sensitivity of the state’s seismographs. This paper^[http://advances.sciencemag.org/content/4/2/e1700578] published in the journal Science Advances shows how effective this technique is - capable of detecting 17 times more earthquakes than older methods in a fraction of the time.
- [The fight against illegal deforestation with TensorFlow (April 2018, Google blog)](https://blog.google/topics/machine-learning/fight-against-illegal-deforestation-tensorflow/)
- [Facebook AI Researchers Detect Flood and Fire Damage from Satellite Imagery (December 2018, VentureBeat)](https://venturebeat.com/2018/12/07/facebook-ai-researchers-detect-flood-and-fire-damage-from-satellite-imagery/)

## Energy

- [Artificial Intelligence and the Future of Energy (Nov 2017, Medium)](https://medium.com/wepower/artificial-intelligence-and-the-future-of-energy-105ac6053de4)
- [How Artificial Intelligence Will Revolutionize the Energy Industry (August 2017, Harvard)](http://sitn.hms.harvard.edu/flash/2017/artificial-intelligence-will-revolutionize-energy-industry/)
- [5 Ways the Energy Industry is Using Artificial Intelligence (March 2018, CB Insights)](https://www.cbinsights.com/research/artificial-intelligence-energy-industry/)
- [This AI Just Mapped Every Solar Panel in the US (December 2018, Gizmodo)](https://gizmodo.com/this-ai-just-mapped-every-solar-panel-in-the-united-sta-1831200756)
- [Google and DeepMind are using AI to predict the energy output of wind farms](https://www.theverge.com/2019/2/26/18241632/google-deepmind-wind-farm-ai-machine-learning-green-energy-efficiency)

## Health

- [Deep learning in biomedicine (August 2018, Nature)](https://drive.google.com/file/d/0B7Js-ioiI0O6akJFX3dMQmRvdm9PYzh6Zk93T2FILUFyb2JZ/view)
- [How open health data can save the NHS (July 2018, Medium)](https://towardsdatascience.com/how-open-health-data-can-save-the-nhs-a2f7059af0f7)
- [Google researchers create AI that maps the brain’s neurons (July 2018, VentureBeat)](https://venturebeat.com/2018/07/16/google-researchers-create-ai-that-maps-the-brains-neurons/)
- [Algorithm matches human cardiologists in detecting heart attacks (July 2018, MIT)](https://www.technologyreview.com/s/611541/algorithm-matches-human-cardiologists-in-detecting-heart-attacks/)
- [Google is training machines to predict when a patient will die (June 2018, LA Times)](http://www.latimes.com/business/technology/la-fi-tn-google-artificial-intelligence-healthcare-20180618-story.html)
- [AI Tools Help the Blind Tackle Everyday Tasks (May 2018, WSJ)](https://www.wsj.com/articles/ai-tools-help-the-blind-tackle-everyday-tasks-1527559620)
- [Can you handle the tooth? AI helps dentists design fake gnashers (May 2018, The Register)](https://www.theregister.co.uk/2018/05/22/ai_generated_teeth_dentists/)
- [London hospitals to replace doctors and nurses with AI for some tasks (May 2018, Guardian)](https://www.theguardian.com/society/2018/may/21/london-hospitals-to-replace-doctors-and-nurses-with-ai-for-some-tasks)
- [AI software that helps doctors diagnose like specialists is approved by FDA (April 2018, The Verge)](https://www.theverge.com/2018/4/11/17224984/artificial-intelligence-idxdr-fda-eye-disease-diabetic-rethinopathy)
- [Google X-ray project shows AI won’t replace doctors any time soon (April 2018, MIT)](https://www.technologyreview.com/s/610552/google-x-ray-project-shows-ai-wont-replace-doctors-any-time-soon/)
- [Using AI to Help Stroke Victims When 'Time Is Brain' (March 2018, Wired)](https://www.wired.com/story/using-ai-to-help-stroke-victims-when-time-is-brain/)
- [Assessing Cardiovascular Risk Factors with Computer Vision (Feb 2018, Google Research)](https://research.googleblog.com/2018/02/assessing-cardiovascular-risk-factors.html)
- [Apple wants to know your heart rate. For science. (Feb 2018, Washington Post)](https://www.washingtonpost.com/news/the-switch/wp/2017/11/30/apple-wants-to-know-your-heart-rate-for-science/?utm_term=.093cac7d132a)
- [Case Study: TensorFlow in Medicine - Retinal Imaging (TensorFlow Dev Summit 2017)](https://www.youtube.com/watch?v=oOeZ7IgEN4o)
- [In our eyes, Google’s software sees heart attack risk (Feb 2018, Washington Post)](https://www.washingtonpost.com/news/the-switch/wp/2018/02/19/google-used-artificial-intelligence-to-predict-heart-attacks-with-the-human-eye/?utm_term=.db4dc29beb7a)

### Research Papers

- [Development and Validation of a Deep Learning Algorithm for Detection of Diabetic Retinopathy in Retinal Fundus Photographs (Dec 2016, JAMA)](https://jamanetwork.com/journals/jama/fullarticle/2588763?guestAccessKey=e95d1518-94df-41f3-a32c-f5ee30e7f3b1)
- [Detecting Cancer Metastases on Gigapixel Pathology Images (March 2017)](https://arxiv.org/abs/1703.02442)
- [Scalable and accurate deep learning for electronic health records (Jan 2018)](https://arxiv.org/abs/1801.07860)
- [Speech recognition for medical conversations (Nov 2017)](https://arxiv.org/abs/1801.07860)
- [Machine-Learned Epidemiology: Real-time Detection of Foodborne Illness at Scale](https://drive.google.com/file/d/1333EiV0iVt1QaYJCgSrI7sE8Oo-juLv7/view)

## Law

- [UK police are using AI to inform custodial decisions – but it could be discriminating against the poor (March 2018, Wired)](http://www.wired.co.uk/article/police-ai-uk-durham-hart-checkpoint-algorithm-edit?utm_content=buffer64913&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)
- [Artificial Intelligence Is Going To Supercharge Surveillance (Jan 2018, The Verge)](https://www.theverge.com/2018/1/23/16907238/artificial-intelligence-surveillance-cameras-security)
- [Sent to Prison by a Software Program’s Secret Algorithms (May 2017, NYT)](https://www.nytimes.com/2017/05/01/us/politics/sent-to-prison-by-a-software-programs-secret-algorithms.html)

## Politics

- [Politics + AI](https://medium.com/politics-ai)

## Robotics

- [This is how the robot uprising finally begins (July 2018, MIT Technology Review)](https://www.technologyreview.com/s/611424/this-is-how-the-robot-uprising-finally-begins/)

## Transportation

- [Learning to navigate in cities without a map (April 2018, DeepMind)](https://deepmind.com/blog/learning-to-navigate-cities-without-a-map/)
